# Generated by Django 4.1 on 2023-07-01 22:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_ticket_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 1))]),
        ),
    ]
