# Generated by Django 4.1 on 2023-07-07 06:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=50, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 7, 7))]),
        ),
    ]
